"""Add admissions and auth refactor

Revision ID: 11a0f26057cc
Revises: 
Create Date: 2026-08-17 11:34:10.110076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a0f26057cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for idempotence ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if not inspector.has_table('admission_workflows'):
        op.create_table('admission_workflows',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=150), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )

    if not inspector.has_table('admission_applications'):
        op.create_table('admission_applications',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('first_name', sa.String(length=120), nullable=False),
            sa.Column('last_name', sa.String(length=120), nullable=False),
            sa.Column('email', sa.String(length=150), nullable=False),
            sa.Column('phone', sa.String(length=50), nullable=True),
            sa.Column('dob', sa.Date(), nullable=True),
            sa.Column('status', sa.String(length=50), nullable=True),
            sa.Column('workflow_id', sa.Integer(), nullable=True),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.ForeignKeyConstraint(['workflow_id'], ['admission_workflows.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admission_applications')
    op.drop_table('admission_workflows')
    # ### end Alembic commands ###
